
mlflow_output_path: "/ebs03/child-mind-institute-detect-sleep-states/mlruns"
experiment_name: "LGBMv001"

num_folds: 5

lgbm_params:
  objective: "binary"
  random_state: 42
  n_estimators: 1000
  verbose: 1